# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3800797a317c39c38dcb530af10772ae7f5a4c97cf81a45fdfa88bbc776246b7ec786a4f345d0d422fd63a3aee3eff30cee1a7c49bc1c716e98e2abe690b1bb3

test:
  secret_key_base: f06a54c38c9eed0646a11df84a12abd04213de52695fbbebfec427cd3b476b7d11e6d35381d77230c2601b376ca670661d06d26df2e936f8eed2e1d389f6e034

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
